# Appveyor build script

version: 1.0.{build}-{branch}

branches:
  except:
    - gh-pages

environment:
  WORK_PATH: .
  TEST_PATH: C:\Libs\test

  
install:
  - md C:\temp
  # Download and install InnoSetup
  - ps: (new-object net.webclient).DownloadFile('http://www.jrsoftware.org/download.php/is.exe?site=1', 'c:\temp\innosetup.exe')
  - dir C:\temp
  # Starting installation
  - c:\temp\innosetup.exe TYPE=full /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /CLOSEAPPLICATIONS /NORESTARTAPPLICATIONS
  # Done 

build_script:
  - iscc src/HackTestWinInstaller.iss
  - dir
 