# Appveyor build script
# List of installed tools/SDKs etc.: https://www.appveyor.com/docs/installed-software

version: 1.0.{build}

# Do not run when just a tag is pushed (which we do automatically by adding a release)
skip_tags: true

branches:
  except:
    - gh-pages

environment:
  WORK_PATH: .
  TEST_PATH: C:\Libs\test

  
install:
  - md C:\temp
  # Download and install InnoSetup (newest version from US site)
  - ps: (new-object net.webclient).DownloadFile('http://www.jrsoftware.org/download.php/is.exe?site=1', 'c:\temp\innosetup.exe')
  - c:\temp\innosetup.exe TYPE=full /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /CLOSEAPPLICATIONS /NORESTARTAPPLICATIONS
  # Add Inno Setup to PATH
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - iscc src/HackTestWinInstaller.iss
  - dir
  
artifacts:
  - path: 'out\*.exe'
  
deploy:
  provider: GitHub
  auth_token:
    secure: 6Ez1BkZ4iDyoY17CZAwbOcQJcKnn8ZWK3vV2QINglWqgkOFRkN4JCtdMu0fyBFMc
  artifact: 'out\*.exe'
  prerelease: true
  tag: v$(appveyor_build_version)
  release: Version $(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE) ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))

  
notifications:
  - provider: Slack
    auth_token:
      secure: ElggvPLQdlcU9+djZsLDZpZLjOOpYg5Y2DRFQGN2yuSrZqoOP/1PCAmUSd8RJjrukymK1FQNrKuSpiw0hLHEeg==
    channel: '#release-info'
  
#done