# Appveyor build script
# List of installed tools/SDKs etc.: https://www.appveyor.com/docs/installed-software

version: 1.1.{build}

# Do not run when just a tag is pushed (which we do automatically by adding a release)
skip_tags: true

branches:
  except:
    - gh-pages

environment:
  WORK_PATH: .
  TEST_PATH: C:\Libs\test

  
install:
  - md C:\temp
  # Download (newest version from US site) and install Inno Setup
  - ps: (new-object net.webclient).DownloadFile('http://www.jrsoftware.org/download.php/is.exe?site=1', 'c:\temp\innosetup.exe')
  - c:\temp\innosetup.exe TYPE=full /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /CLOSEAPPLICATIONS /NORESTARTAPPLICATIONS
  # Add Inno Setup to PATH so the ISCC command is found
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
  # Install CURL
  - choco install -y curl 
  # Download newest version of the font files
  # Curl options: 
  #     k - **Disable SSL check** because else the download fails
  #     L - follow redirects 
  #     O - Use external file name
  - cd %APPVEYOR_BUILD_FOLDER%\testfonts
  - dir
  - curl -kLO https://github.com/chrissimpkins/Hack/raw/master/build/test_builds/Hack-Bold-DEV.ttf
  - dir 
    

build_script:
  - iscc.exe /DEXTERNAL_VERSION=%APPVEYOR_BUILD_VERSION% src/HackWindowsInstaller.iss
  # - dir

  
artifacts:
  - path: 'out\*.exe'
    name: SetupExe
  
deploy:
  provider: GitHub
  auth_token:
    secure: 6Ez1BkZ4iDyoY17CZAwbOcQJcKnn8ZWK3vV2QINglWqgkOFRkN4JCtdMu0fyBFMc
  artifact: SetupExe
  prerelease: true
  tag: v$(appveyor_build_version)
  release: Version $(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE) ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))

  
notifications:
  - provider: Slack
    auth_token:
      secure: ElggvPLQdlcU9+djZsLDZpZLjOOpYg5Y2DRFQGN2yuSrZqoOP/1PCAmUSd8RJjrukymK1FQNrKuSpiw0hLHEeg==
    channel: '#release-info'
  
#done